." Manpage for caesarcipher
.".RI [ underlined ]
.TH caesarcipher 1 "February 2017" "caesarcipher 1.0" "Manpage for caesarcipher"
.SH NAME
caesarcipher \- Caesar cipher cryptography tool
.SH SYNOPSIS
.BR "caesarcipher " "[-d || -e [-s shiftvalue] [-i inputfile] [-o outputfile] message ...]"
.SH DESCRIPTION
caesarcipher is an implementation of the Caesar cipher algorithm over the entire set of printable ASCII characters.
.PP
.B \fIProgram Invocation\fR:
caesarcipher can be invoked in the folloging three forms:
.PP
\fI1st Form\fR: If invoked with no other arguments, than a possible shiftvalue \fB-s\fR, the user is placed into a shell like command line enviroment, in which he can enter messages to be decrypted or encrypted.
.PP
The "caesarcipher shell" which identifies itself by:
.B "cc>"
knows the following commands:
.PP
.TP
.BR 	ascii " - print the ascii table."
.TP
.BR 	decrypt " - decrypt the message in the message buffer or specify a new one."
.TP
.BR 	encrypt " - encrypt the message in the message buffer or specify a new one."
.TP
.BR 	exit " - exit caesarcipher."
.TP
.BR 	help " - print the command menu."
.TP
.BR		print " - print the current shift table."
.TP
.BR 	shift " - set a new shiftvalue."
.TP
.BR 	quit " - quit caesarcipher (same as exit)."
.PP
\fI2nd Form\fR: In this form, the utility is invoked with either the \fB-d\fR or \fB-e\fR switch, to decrypt or encrypt messages passed on the command line with a given shift value \fB-s\fR.
.PP
\fI3rd Form\fR: If the the message to be decoded/encoded resides inside a file, then caesarcipher can, alongside the \fB-d\fR or \fB-e\fR switches, be invoked with the \fB-i \fR switch, which takes an associated \fBinputfile\fR argument. If \fB-o outputfile\fR is specified as well, then the decoded/encoded message is written to the outputfile. Otherwise the message is written to stdout.
.PP
.SH OPTIONS
.TP
.B -d, --decrypt
decrypt the message or inputfile
.TP
.B -e, --encrypt
encrypt the message or inputfile
.TP
.B -h, --help
print a help message and exit
.TP
.BR "-i, --inputfile="inputfile
read from the following input file
.TP
.BR "-o, --outputfile="inputfile
write to the following outputfile
.TP
.BR "-s, --shift="shiftvalue
set the shiftvalue
.SH THEORY
.PP
The cipher works by shifting the characters in the original message by a certain number, to create a new encrypted message.
.PP
Take for example the letters from A-Z (the original alphabet), and another alphabet (the shifted alphabet), in which each letter has been shifted (adding) by the number 5 (the encryption key):
.PP
.B	Original Alphabet:		Shifted Alphabet:
.br
		A					F
.br
		B					G
.br
		C					H
.br
		D					I
.br
		E					J
.br
		F					K
.br
		G					L
.br
		H					M
.br
		I					N
.br
		J					O
.br
		K					P
.br
		L					Q
.br
		M					R
.br
		N					S
.br
		O					T
.br
		P					U
.br
		Q					V
.br
		R					W
.br
		S					X
.br
		T					Y
.br
		U					Z
.br
		V					A
.br
		W					B
.br
		X					C
.br
		Y					D
.br
		Z					E
.PP
Suppose now, that the message to encrypt is:
.B "THIS IS THE SECRET MESSAGE"
.PP
By making use of the above substitution, every character gets shifted by 5 as in the shifted alphabet.
.PP
The encrypted message therefore becomes:
.B "YMNX NX YMJ XJHWJY RJXXFLJ"
.PP
To decrypt the message, knowledge of the shift value/encryption key is required. Decryption works shifting backwards (subtracting) the given encryption key from every letter, thus obtaining the original message.
.PP
Whereas the classical Caesar cipher only used capital letters from A-Z, as in the example above, this implementation is capable of mapping all displayable ASCII characters (Hex 20 - Hex 7E).
.PP
Note however, that caesarcipher should
.B not be used for serious encryption purposes,
as the algorithm is not inherently safe.
.PP
The Caesar cipher has been named after Julius Caesar (100 BC - 44 BC).
.SH BUGS
Please report when found.
.SH AUTHOR
Oliver Mahmoudi (contact@olivermahmoudi.com)
