." Manpage for caesarcipher
.".RI [ underlined ]
.TH caesarcipher 1 "June 2020" "caesarcipher 1.1" "Manpage for caesarcipher"
.SH NAME
caesarcipher \- Caesar cipher cryptography tool
.SH SYNOPSIS
.BR "caesarcipher " "[-d|-e] [-p] [-s shiftvalue] [-i inputfile] [-o outputfile] [message ...]"
.SH DESCRIPTION
caesarcipher is an implementation of the Caesar cipher encryption algorithm extended to the entire set of printable ASCII characters.
.PP
.B \fIProgram Invocation\fR:
caesarcipher can be invoked in the following three forms:
.PP
\fI1st Form\fR: If invoked with no arguments, other than a possible shiftvalue \fB-s\fR or the \fB-p\fR option, the user is placed into a shell like command line enviroment, in which he can enter messages to be encrypted or decrypted.
.PP
The "caesarcipher shell" which identifies itself by:
.B "cc>"
understands the following commands:
.PP
.TP
.BR 	ascii " - print the ASCII table."
.TP
.BR 	decrypt " - enter a message to decrypt."
.TP
.BR 	encrypt " - enter a message to encrypt."
.TP
.BR 	exit " - exit caesarcipher."
.TP
.BR 	help " - print the command menu."
.TP
.BR		shifttable " - print the current shift table."
.TP
.BR 	shiftvalue " - set a new shiftvalue."
.TP
.BR		spaces " - turn preserve spaces on/off."
.TP
.BR 	quit " - quit caesarcipher (same as exit)."
.PP
\fI2nd Form\fR: In this form, the utility is invoked with either the \fB-d\fR or \fB-e\fR switch, a given shift value \fB-s\fR to encrypt or decrypt messages passed via the command line.
.PP
\fI3rd Form\fR: If the message to be processed is inside a file, then caesarcipher can, alongside the \fB-d\fR or \fB-e\fR switches, be invoked with the \fB-i \fR option, which takes an associated \fBinputfile\fR argument. If \fB-o outputfile\fR is specified as well, then the encoded/decoded message is written to the outputfile. Otherwise the message is written to stdout.
.PP
.SH OPTIONS
.TP
.B -d, --decrypt
decrypt the message or inputfile
.TP
.B -e, --encrypt
encrypt the message or inputfile
.TP
.B -h, --help
print a help message and exit
.TP
.BR "-i inputfile, --inputfile="inputfile
read from inputfile
.TP
.BR "-o outputfile, --outputfile="outputfile
write to outputfile
.TP
.B -p, --preserve-spaces
preserve spaces when decoding/encoding
.TP
.BR "-s shiftvalue, --shiftvalue="shiftvalue
set the shiftvalue
.SH THEORY
.PP
The cipher works by shifting the characters in the original message by a certain number, thus creating a new - encrypted - message.
.PP
Take for example the letters from A-Z (original alphabet), and another alphabet (shifted alphabet), in which each letter has been shifted by the number 5 (shiftvalue):
.PP
.B	Original Alphabet:		Shifted Alphabet:
.br
		A					F
.br
		B					G
.br
		C					H
.br
		D					I
.br
		E					J
.br
		F					K
.br
		G					L
.br
		H					M
.br
		I					N
.br
		J					O
.br
		K					P
.br
		L					Q
.br
		M					R
.br
		N					S
.br
		O					T
.br
		P					U
.br
		Q					V
.br
		R					W
.br
		S					X
.br
		T					Y
.br
		U					Z
.br
		V					A
.br
		W					B
.br
		X					C
.br
		Y					D
.br
		Z					E
.PP
Suppose now, that the message to encrypt is:
.B "THIS IS THE SECRET MESSAGE"
.PP
By making use of the above table, every character of the original message can be mapped to its corresponding character in the shifted alphabet.
.PP
The encrypted message therefore becomes:
.B "YMNX NX YMJ XJHWJY RJXXFLJ"
.PP
To decrypt a message, knowledge of the shiftvalue (encryption key) is required. Decryption works by reverse shifting (subtracting) the given encryption key from every letter, thus obtaining the original message.
.PP
Whereas the classical Caesar cipher only uses capital letters from A-Z, as in the example above, this implementation is capable of transforming all displayable ASCII characters (Hex 20 - Hex 7E).
.PP
Note however, that caesarcipher should
.B not be used for serious encryption purposes,
as the algorithm is not inherently safe.
.PP
The Caesar cipher is named after Julius Caesar (100 BC - 44 BC).
.SH EXAMPLES
.PP
1. Encode the message: "Secret Message" with a shift value of 21 and write it to stdout.
.PP
caesarcipher -e -s 21 "Secret Message"
.PP
2. Decode the string "123456789" with a shift value of 1.
.PP
caesarcipher -d -s 1 123456789
.PP
3. Encode the contents of file orig.txt with a shift value of -179 and preserve spaces. Write the result to encrypted.txt.
.PP
caesarcipher -e -s -179 -p -i ~/orig.txt -o ~/encrypted.txt
.SH AUTHOR
Oliver Mahmoudi (contact@olivermahmoudi.com)
